kind: PersistentVolume
apiVersion: v1
metadata:
  name: orderer-pv
  labels:
    type: local
    name: ordererfiles
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/orderer/var/hyperledger/production
    server: storage.local.parisi.biz
    readOnly: false
