kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: server-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: serverfiles
