kind: PersistentVolume
apiVersion: v1
metadata:
  name: studentpeer1-pv
  labels:
    type: local
    name: studentpeer1files
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/studentpeer1/var
    server: storage.local.parisi.biz
    readOnly: false
